// Generated by TableGenerator

using System;
using System.Collections.Generic;
using SqlBuilderFramework;

namespace SqlBuilderSamplesAndTests
{
    public class Tblbrands : DbTable
    {
        public override string Name => "BRANDS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<int?> Colbrand_id => new DbTypedColumn<int?>(new DbTableColumn(this, "brand_id", 0, 0));
        public DbTypedColumn<string> Colbrand_name => new DbTypedColumn<string>(new DbTableColumn(this, "brand_name", 255, 0));
    }

    public class Tblcategories : DbTable
    {
        public override string Name => "CATEGORIES";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<int?> Colcategory_id => new DbTypedColumn<int?>(new DbTableColumn(this, "category_id", 0, 0));
        public DbTypedColumn<string> Colcategory_name => new DbTypedColumn<string>(new DbTableColumn(this, "category_name", 255, 0));
    }

    public class Tblcustomers : DbTable
    {
        public override string Name => "CUSTOMERS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<string> Colcity => new DbTypedColumn<string>(new DbTableColumn(this, "city", 50, 0));
        public DbTypedColumn<int?> Colcustomer_id => new DbTypedColumn<int?>(new DbTableColumn(this, "customer_id", 0, 0));
        public DbTypedColumn<string> Colemail => new DbTypedColumn<string>(new DbTableColumn(this, "email", 255, 0));
        public DbTypedColumn<string> Colfirst_name => new DbTypedColumn<string>(new DbTableColumn(this, "first_name", 255, 0));
        public DbTypedColumn<string> Collast_name => new DbTypedColumn<string>(new DbTableColumn(this, "last_name", 255, 0));
        public DbTypedColumn<string> Colphone => new DbTypedColumn<string>(new DbTableColumn(this, "phone", 25, 0));
        public DbTypedColumn<string> Colstate => new DbTypedColumn<string>(new DbTableColumn(this, "state", 25, 0));
        public DbTypedColumn<string> Colstreet => new DbTypedColumn<string>(new DbTableColumn(this, "street", 255, 0));
        public DbTypedColumn<string> Colzip_code => new DbTypedColumn<string>(new DbTableColumn(this, "zip_code", 5, 0));
    }

    public class Tblorder_items : DbTable
    {
        public override string Name => "ORDER_ITEMS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<decimal> Coldiscount => new DbTypedColumn<decimal>(new DbTableColumn(this, "discount", 4, 2));
        public DbTypedColumn<int?> Colitem_id => new DbTypedColumn<int?>(new DbTableColumn(this, "item_id", 0, 0));
        public DbTypedColumn<decimal> Collist_price => new DbTypedColumn<decimal>(new DbTableColumn(this, "list_price", 10, 2));
        public DbTypedColumn<int?> Colorder_id => new DbTypedColumn<int?>(new DbTableColumn(this, "order_id", 0, 0));
        public DbTypedColumn<int> Colproduct_id => new DbTypedColumn<int>(new DbTableColumn(this, "product_id", 0, 0));
        public DbTypedColumn<int> Colquantity => new DbTypedColumn<int>(new DbTableColumn(this, "quantity", 0, 0));
    }

    public class Tblorders : DbTable
    {
        public override string Name => "ORDERS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<int?> Colcustomer_id => new DbTypedColumn<int?>(new DbTableColumn(this, "customer_id", 0, 0));
        public DbTypedColumn<DateTime> Colorder_date => new DbTypedColumn<DateTime>(new DbTableColumn(this, "order_date", 0, 0));
        public DbTypedColumn<int?> Colorder_id => new DbTypedColumn<int?>(new DbTableColumn(this, "order_id", 0, 0));
        public DbTypedColumn<int> Colorder_status => new DbTypedColumn<int>(new DbTableColumn(this, "order_status", 0, 0));
        public DbTypedColumn<DateTime> Colrequired_date => new DbTypedColumn<DateTime>(new DbTableColumn(this, "required_date", 0, 0));
        public DbTypedColumn<DateTime?> Colshipped_date => new DbTypedColumn<DateTime?>(new DbTableColumn(this, "shipped_date", 0, 0));
        public DbTypedColumn<int> Colstaff_id => new DbTypedColumn<int>(new DbTableColumn(this, "staff_id", 0, 0));
        public DbTypedColumn<int> Colstore_id => new DbTypedColumn<int>(new DbTableColumn(this, "store_id", 0, 0));
    }

    public class Tblproducts : DbTable
    {
        public override string Name => "PRODUCTS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<int> Colbrand_id => new DbTypedColumn<int>(new DbTableColumn(this, "brand_id", 0, 0));
        public DbTypedColumn<int> Colcategory_id => new DbTypedColumn<int>(new DbTableColumn(this, "category_id", 0, 0));
        public DbTypedColumn<decimal> Collist_price => new DbTypedColumn<decimal>(new DbTableColumn(this, "list_price", 10, 2));
        public DbTypedColumn<int> Colmodel_year => new DbTypedColumn<int>(new DbTableColumn(this, "model_year", 0, 0));
        public DbTypedColumn<int?> Colproduct_id => new DbTypedColumn<int?>(new DbTableColumn(this, "product_id", 0, 0));
        public DbTypedColumn<string> Colproduct_name => new DbTypedColumn<string>(new DbTableColumn(this, "product_name", 255, 0));
    }

    public class TblRefreshToken : DbTable
    {
        public override string Name => "REFRESHTOKEN";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<DateTime> ColCreated => new DbTypedColumn<DateTime>(new DbTableColumn(this, "Created", 0, 0));
        public DbTypedColumn<string> ColCreatedByIp => new DbTypedColumn<string>(new DbTableColumn(this, "CreatedByIp", 40, 0));
        public DbTypedColumn<DateTime> ColExpires => new DbTypedColumn<DateTime>(new DbTableColumn(this, "Expires", 0, 0));
        public DbTypedColumn<string> ColReplacedByToken => new DbTypedColumn<string>(new DbTableColumn(this, "ReplacedByToken", 100, 0));
        public DbTypedColumn<DateTime?> ColRevoked => new DbTypedColumn<DateTime?>(new DbTableColumn(this, "Revoked", 0, 0));
        public DbTypedColumn<string> ColRevokedByIp => new DbTypedColumn<string>(new DbTableColumn(this, "RevokedByIp", 40, 0));
        public DbTypedColumn<string> ColToken => new DbTypedColumn<string>(new DbTableColumn(this, "Token", 100, 0));
        public DbTypedColumn<int> ColUserId => new DbTypedColumn<int>(new DbTableColumn(this, "UserId", 0, 0));
    }

    public class Tblstaffs : DbTable
    {
        public override string Name => "STAFFS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<int> Colactive => new DbTypedColumn<int>(new DbTableColumn(this, "active", 0, 0));
        public DbTypedColumn<string> Colemail => new DbTypedColumn<string>(new DbTableColumn(this, "email", 255, 0));
        public DbTypedColumn<string> Colfirst_name => new DbTypedColumn<string>(new DbTableColumn(this, "first_name", 50, 0));
        public DbTypedColumn<string> Collast_name => new DbTypedColumn<string>(new DbTableColumn(this, "last_name", 50, 0));
        public DbTypedColumn<int?> Colmanager_id => new DbTypedColumn<int?>(new DbTableColumn(this, "manager_id", 0, 0));
        public DbTypedColumn<string> Colphone => new DbTypedColumn<string>(new DbTableColumn(this, "phone", 25, 0));
        public DbTypedColumn<int?> Colstaff_id => new DbTypedColumn<int?>(new DbTableColumn(this, "staff_id", 0, 0));
        public DbTypedColumn<int> Colstore_id => new DbTypedColumn<int>(new DbTableColumn(this, "store_id", 0, 0));
    }

    public class Tblstocks : DbTable
    {
        public override string Name => "STOCKS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<int?> Colproduct_id => new DbTypedColumn<int?>(new DbTableColumn(this, "product_id", 0, 0));
        public DbTypedColumn<int?> Colquantity => new DbTypedColumn<int?>(new DbTableColumn(this, "quantity", 0, 0));
        public DbTypedColumn<int?> Colstore_id => new DbTypedColumn<int?>(new DbTableColumn(this, "store_id", 0, 0));
    }

    public class Tblstores : DbTable
    {
        public override string Name => "STORES";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<string> Colcity => new DbTypedColumn<string>(new DbTableColumn(this, "city", 255, 0));
        public DbTypedColumn<string> Colemail => new DbTypedColumn<string>(new DbTableColumn(this, "email", 255, 0));
        public DbTypedColumn<string> Colphone => new DbTypedColumn<string>(new DbTableColumn(this, "phone", 25, 0));
        public DbTypedColumn<string> Colstate => new DbTypedColumn<string>(new DbTableColumn(this, "state", 10, 0));
        public DbTypedColumn<int?> Colstore_id => new DbTypedColumn<int?>(new DbTableColumn(this, "store_id", 0, 0));
        public DbTypedColumn<string> Colstore_name => new DbTypedColumn<string>(new DbTableColumn(this, "store_name", 255, 0));
        public DbTypedColumn<string> Colstreet => new DbTypedColumn<string>(new DbTableColumn(this, "street", 255, 0));
        public DbTypedColumn<string> Colzip_code => new DbTypedColumn<string>(new DbTableColumn(this, "zip_code", 5, 0));
    }

    public class TblUsers : DbTable
    {
        public override string Name => "USERS";

        public override string Sql(List<ParameterEntity> parameterList, ISqlBuilder query, IDatabase database)
        {
            return Name;
        }

        public override DbTable Find(ISqlBuilder query)
        {
            return null;
        }

        public DbTypedColumn<string> ColFirstName => new DbTypedColumn<string>(new DbTableColumn(this, "FirstName", 60, 0));
        public DbTypedColumn<int> ColId => new DbTypedColumn<int>(new DbTableColumn(this, "Id", 0, 0));
        public DbTypedColumn<bool> ColIsActive => new DbTypedColumn<bool>(new DbTableColumn(this, "IsActive", 0, 0));
        public DbTypedColumn<string> ColLastName => new DbTypedColumn<string>(new DbTableColumn(this, "LastName", 60, 0));
        public DbTypedColumn<string> ColPassword => new DbTypedColumn<string>(new DbTableColumn(this, "Password", 60, 0));
        public DbTypedColumn<string> ColRole => new DbTypedColumn<string>(new DbTableColumn(this, "Role", 20, 0));
        public DbTypedColumn<string> ColUsername => new DbTypedColumn<string>(new DbTableColumn(this, "Username", 25, 0));
    }

    public static class Tables
    {
        public static Tblbrands brands = new Tblbrands();
        public static Tblcategories categories = new Tblcategories();
        public static Tblcustomers customers = new Tblcustomers();
        public static Tblorder_items order_items = new Tblorder_items();
        public static Tblorders orders = new Tblorders();
        public static Tblproducts products = new Tblproducts();
        public static TblRefreshToken RefreshToken = new TblRefreshToken();
        public static Tblstaffs staffs = new Tblstaffs();
        public static Tblstocks stocks = new Tblstocks();
        public static Tblstores stores = new Tblstores();
        public static TblUsers Users = new TblUsers();
    }
}
